services:
  bubble-quiz:
    image: ghcr.io/somecodecat/bubble-quiz:latest
    container_name: bubble-quiz
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
    environment:
      - DATABASE_URL=file:/app/data/db.sqlite
      - NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:3000
      # Generate a secret with `openssl rand -base64 32`
      - NEXTAUTH_SECRET=changeme
      # Backup Configuration
      - BACKUP_SCHEDULE=0 0 * * *
      - BACKUP_DIR=/app/backups
      - BACKUP_RETENTION=5
      # Add other providers if needed
      # - AUTH_GOOGLE_ID=
      # - AUTH_GOOGLE_SECRET=
      # - AUTH_DISCORD_ID=
      # - AUTH_DISCORD_SECRET=
      # - AUTHENTIK_ISSUER=
      # - AUTHENTIK_CLIENT_ID=
      # - AUTHENTIK_CLIENT_SECRET=
      # - CRON_SECRET=
